#
#   Mystery Mob Spawner
#   ● Requires Silk Spawner
#
# Created by ProfCube 
#
# This Config can be used with Free/Paid version
# of CrateReloaded. If you have any question PM
# me on discord or make a threat on GitHub about
# the config so I can help you out.
#
#        COPY FROM BELLOW THIS COMMENT         #

MMS:
    type: MYSTERYCRATE # Set this crate to a block, and players may right click the block to use "keys"
    item: 'SPAWNER 1 name:&6&lMysteryMobSpawner lore:&7Right-click_in_hand_to_reveal_one|&7of_the_following_mob_spawner_types:||&6&lx_&7Pig|&6&lx_&7Cow|&6&lx_&7Sheep|&6&lx_&7Chicken|&6&lx_&7Wolf|&6&lx_&7Mooshroom|&6&lx_&7Ocelot|&6&lx_&eIronGolem|&6&lx_&eWitch|&6&lx_&eCreeper|&6&lx_&eSkeleton|&6&lx_&eSpider|&6&lx_&eZombie|&6&lx_&eZombiePigman|&6&lx_&eEndermand|&6&lx_&eBlaze|&6&lx_&eMagmaCube||&7More_can_be_bought_@_&e&nstore.NAMEHERE.com glow:true'
    animation: 'Rectangle'
    confirmation:
        enabled: false
        accept-button: 'GREEN_STAINED_GLASS_PANE 1 name:&aYes lore:&fClick_here_to_open_{crate}!'
        decline-button: 'RED_STAINED_GLASS_PANE 1 name:&4No'
    preview:
        enabled: false
        rows: 0
    buy:
        enabled: false
        cost: 0
    message:
        open: '&7You have opened a &6&lMysteryMobSpawner'
        broadcast: ''
    effect:
        1:
          class: Original
          category: PERSISTENT
        2:
          class: Sound
          category: ANIMATION
          sound: BLOCK_WOOD_PLACE
        3:
          class: Sound
          sound: ENTITY_BAT_TAKEOFF
          CATEGORY: END
    reward:
        minimum-rewards: 1
        maximum-rewards: 1
        rewards:
            - 'unique:(),     chance:(1),           cmd:(ss give %player% Pig 1),   display:(SPAWNER 1 name:&7Spawner: lore:&e&lPig)'
            - 'unique:(),     chance:(1),           cmd:(ss give %player% Cow 1),   display:(SPAWNER 1 name:&7Spawner: lore:&e&lCow)'
            - 'unique:(),     chance:(1),           cmd:(ss give %player% Sheep 1),   display:(SPAWNER 1 name:&7Spawner: lore:&e&lSheep)'
            - 'unique:(),     chance:(1),           cmd:(ss give %player% Chicken 1),   display:(SPAWNER 1 name:&7Spawner: lore:&e&lChicken)'
            - 'unique:(),     chance:(1),           cmd:(ss give %player% Wolf 1),   display:(SPAWNER 1 name:&7Spawner: lore:&e&lWolf)'
            - 'unique:(),     chance:(1),           cmd:(ss give %player% Mooshroom 1),   display:(SPAWNER 1 name:&7Spawner: lore:&e&lMooshroom)'
            - 'unique:(),     chance:(1),           cmd:(ss give %player% Ocelot 1),   display:(SPAWNER 1 name:&7Spawner: lore:&e&lOcelot)'
            - 'unique:(),     chance:(1),           cmd:(ss give %player% IronGolem 1),   display:(SPAWNER 1 name:&7Spawner: lore:&e&lIronGolem)'
            - 'unique:(),     chance:(1),           cmd:(ss give %player% Witch 1),   display:(SPAWNER 1 name:&7Spawner: lore:&e&lWitch)'
            - 'unique:(),     chance:(1),           cmd:(ss give %player% Creeper 1),   display:(SPAWNER 1 name:&7Spawner: lore:&e&lCreeper)'
            - 'unique:(),     chance:(1),           cmd:(ss give %player% Skeleton 1),   display:(SPAWNER 1 name:&7Spawner: lore:&e&lSkeleton)'
            - 'unique:(),     chance:(1),           cmd:(ss give %player% Spider 1),   display:(SPAWNER 1 name:&7Spawner: lore:&e&lSpider)'
            - 'unique:(),     chance:(1),           cmd:(ss give %player% Zombie 1),   display:(SPAWNER 1 name:&7Spawner: lore:&e&lZombie)'
            - 'unique:(),     chance:(1),           cmd:(ss give %player% ZombePigman 1),   display:(SPAWNER 1 name:&7Spawner: lore:&e&lZombiePigman)'
            - 'unique:(),     chance:(1),           cmd:(ss give %player% Enderman 1),   display:(SPAWNER 1 name:&7Spawner: lore:&e&lEnderman)'
            - 'unique:(),     chance:(1),           cmd:(ss give %player% Blaze 1),   display:(SPAWNER 1 name:&7Spawner: lore:&e&lBlaze)'
            - 'unique:(),     chance:(1),           cmd:(ss give %player% MagmaCube 1),   display:(SPAWNER 1 name:&7Spawner: lore:&e&lMagmaCube)'


##########################################################################################################
# USE THIS VERSION BELLOW IF YOU ARE ON VERSION 1.0 OF CRATES RELOADED THE VERSION ABOVE WONT WORK ON IT #
##########################################################################################################


MMS:
    type: MYSTERYCRATE
    buy:
        enabled: false
        cost: 0
    message:
        onOpen: ''
        broadcast: ''
    item:
        item: 52
        enchantment: '300:1'
        name: '&6&lMysteryMobSpawner'
        lore:
            - '&7Right-click in hand to reveal one'
            - '&7of the following mob spawner types:'
            - ''
            - '&6&lx &7Pig'
            - '&6&lx &7Cow'
            - '&6&lx &7Sheep'
            - '&6&lx &7Chicken'
            - '&6&lx &7Wolf'
            - '&6&lx &7Mooshroom'
            - '&6&lx &7Ocelot'
            - '&6&lx &eIronGolem'
            - '&6&lx &eWitch'
            - '&6&lx &eCreeper'
            - '&6&lx &eSkeleton'
            - '&6&lx &eSpider'
            - '&6&lx &eZombie'
            - '&6&lx &eZombiePigman'
            - '&6&lx &eEndermand'
            - '&6&lx &eBlaze'
            - '&6&lx &eMagmaCube'
            - ''
            - '&7More can be bought @ &e&nstore.NAMEHERE.com'
    effect:
        onOpenEffects: 'witchMagic, CLICK'
        dormantEffects: ''
    reward:
        minimumRewards: 1
        maximumRewards: 1
        rewards:
            - 'cmd:(/ss give %player% Pig), chance:(0.5), noduplicate:() display:(mob_spawner 1 &a&lSpawner&8:&c&lPig), onopen:(&7You have received &6&l1 Pig Spawner)'
            - 'cmd:(/ss give %player% Cow), chance:(0.5), noduplicate:() display:(mob_spawner 1 &a&lSpawner&8:&c&lCow), onopen:(&7You have received &6&l1 Cow Spawner)'
            - 'cmd:(/ss give %player% Sheep), chance:(0.5), noduplicate:() display:(mob_spawner 1 &a&lSpawner&8:&c&lSheep), onopen:(&7You have received &6&l1 Sheep Spawner)'
            - 'cmd:(/ss give %player% Chicken), chance:(0.5), noduplicate:() display:(mob_spawner 1 &a&lSpawner&8:&c&lChicken), onopen:(&7You have received &6&l1 Pig Spawner)'
            - 'cmd:(/ss give %player% Wolf), chance:(0.5), noduplicate:() display:(mob_spawner 1 &a&lSpawner&8:&c&lWolf), onopen:(&7You have received &6&l1 Wolf Spawner)'
            - 'cmd:(/ss give %player% Mooshroom), chance:(0.5), noduplicate:() display:(mob_spawner 1 &a&lSpawner&8:&c&lMooshroom), onopen:(&7You have received &6&l1 Mooshroom Spawner)'
            - 'cmd:(/ss give %player% Ocelot), chance:(0.5), noduplicate:() display:(mob_spawner 1 &a&lSpawner&8:&c&lOcelot), onopen:(&7You have received &6&l1 Ocelot Spawner)'
            - 'cmd:(/ss give %player% IronGolem), chance:(0.5), noduplicate:() display:(mob_spawner 1 &a&lSpawner&8:&c&lIronGolem), onopen:(&7You have received &6&l1 IronGolem Spawner)'
            - 'cmd:(/ss give %player% Witch), chance:(0.5), noduplicate:() display:(mob_spawner 1 &a&lSpawner&8:&c&lWitch), onopen:(&7You have received &6&l1 Witch Spawner)'
            - 'cmd:(/ss give %player% Creeper), chance:(0.5), noduplicate:() display:(mob_spawner 1 &a&lSpawner&8:&c&lCreeper), onopen:(&7You have received &6&l1 Creeper Spawner)'
            - 'cmd:(/ss give %player% Skeleton), chance:(0.5), noduplicate:()display:(mob_spawner 1 &a&lSpawner&8:&c&lSkeleton), onopen:(&7You have received &6&l1 Skeleton Spawner)'
            - 'cmd:(/ss give %player% Spider), chance:(0.5), noduplicate:() display:(mob_spawner 1 &a&lSpawner&8:&c&lSpider), onopen:(&7You have received &6&l1 Spider Spawner)'
            - 'cmd:(/ss give %player% Zombie), chance:(0.5), noduplicate:() display:(mob_spawner 1 &a&lSpawner&8:&c&lZombie), onopen:(&7You have received &6&l1 Zombie Spawner)'
            - 'cmd:(/ss give %player% ZombePigman), chance:(0.5), noduplicate:() display:(mob_spawner 1 &a&lSpawner&8:&c&lZombiePigman), onopen:(&7You have received &6&l1 ZombiePigman Spawner)'
            - 'cmd:(/ss give %player% Enderman), chance:(0.5), noduplicate:() display:(mob_spawner 1 &a&lSpawner&8:&c&lEnderman), onopen:(&7You have received &6&l1 Enderman Spawner)'
            - 'cmd:(/ss give %player% Blaze), chance:(0.5), noduplicate:() display:(mob_spawner 1 &a&lSpawner&8:&c&lBlaze), onopen:(&7You have received &6&l1 Blaze Spawner)'
            - 'cmd:(/ss give %player% MagmaCube), chance:(0.5), noduplicate:() display:(mob_spawner 1 &a&lSpawner&8:&c&lMagmaCube), onopen:(&7You have received &6&l1 MagmaCube Spawner)'
